### ISSUE TITLE
External Epitope prediction on Mac

### ISSUE THREAD

**Issue by linusb** [FRED-2/Fred2#113]
I try to predict a list of peptides with netMHCpan-2.8 using this code:
```python
from Fred2.Core import Allele, Peptide
from Fred2.IO import read_lines
from Fred2.EpitopePrediction import EpitopePredictorFactory

# reading input
peptides2 = read_lines("./peptides.txt", in_type=Peptide)
alleles = read_lines("./alleles.txt", in_type=Allele)
# prediction
predictor = EpitopePredictorFactory("netmhcpan", version="2.8")
results = predictor.predict(peptides=peptides2, alleles=alleles, command="my_path/netMHCpan-2.8/netMHCpan")
results.head()
```

It does the prediction but crashes at:
```python
Traceback (most recent call last):  
  File "my_path/netMHCpan_knime_node/netMHCpan_knime_node.py", line 19, in <module>
    results = predictor.predict(peptides=peptides2, alleles=alleles, command="my_path/netMHCpan_knime_node/netMHCpan-2.8/netMHCpan")
  File "my_path/knime_node_env/lib/python2.7/site-packages/Fred2/EpitopePrediction/External.py", line 159, in predict
    res_tmp = self.parse_external_result(tmp_out.name)
  File "my_path/knime_node_env/lib/python2.7/site-packages/Fred2/EpitopePrediction/External.py", line 1264, in parse_external_result
    alleles = set(filter(lambda x: x != "", f.next()))
StopIteration
```

**Comment by linusb** [comment]
This also does not work on Linux

**Comment by linusb** [comment]
Problem was caused by PyCharm and not FRED2 or netMHCpan. Looks like a virtual environment hickup.
