### ISSUE TITLE
pandas dataframe index is incompatible with Fred2.Core.Peptide

### ISSUE THREAD

**Issue by mwalzer** [FRED-2/Fred2#15]
use str(...) instead - how did this even work for anyone!?
see https://github.com/FRED-2/Fred2/blob/master/Fred2/EpitopePrediction/PSSM.py#L80

**Comment by b-schubert** [comment]
works for me (pandas version 0.16.2)

**Comment by mwalzer** [comment]
not for me - same pandas version 
```>>> pd.__version__
'0.16.2'```

and this produces e.g. 
```
======================================================================
FAIL: test_syf (Fred2.test.TestEpitopePrediction.TestCaseEpitopePrediction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/Fred2/test/TestEpitopePrediction.py", line 32, in test_syf
    print EpitopePredictorFactory("Syfpeithi").predict(self.peptides_mhcI, self.mhcI)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/Fred2/EpitopePrediction/PSSM.py", line 122, in predict
    return super(Syfpeithi, self).predict(peptides, alleles=alleles, **kwargs)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/Fred2/EpitopePrediction/PSSM.py", line 88, in predict
    df_result = EpitopePredictionResult.from_dict(result)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 683, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 214, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 341, in _init_dict
    dtype=dtype)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 4798, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 4841, in extract_index
    index = _union_indexes(indexes)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/index.py", line 5774, in _union_indexes
    return _unique_indices(indexes)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/index.py", line 5755, in _unique_indices
    return Index(lib.fast_unique_multiple_list([ conv(i) for i in inds ]))
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/index.py", line 168, in __new__
    sorted(data)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/Bio/Seq.py", line 206, in __lt__
    other.alphabet]):
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/Bio/Alphabet/__init__.py", line 392, in _check_type_compatible
    a = _get_base_alphabet(alpha)
  File "/home/walzer/pyvenvs/Fred2-venv/local/lib/python2.7/site-packages/Bio/Alphabet/__init__.py", line 245, in _get_base_alphabet
    "Invalid alphabet found, %s" % repr(a)
AssertionError: Invalid alphabet found, <class 'Bio.Alphabet.IUPAC.IUPACProtein'>

----------------------------------------------------------------------
Ran 1 test in 0.020s

```

**Comment by b-schubert** [comment]
and what biopython are you running?

mine is: 

>>> Bio.__version__
'1.63'

**Comment by mwalzer** [comment]
Bio is '1.65'
But since the pd dataframes also lean against numpy structures that might be of relevance - version '1.9.2'

**Comment by b-schubert** [comment]
dont know my version is even older: 
```
numpy.__version__
'1.8.0rc1'
```

**Comment by mwalzer** [comment]
:unamused:

**Comment by mwalzer** [comment]
Also does not work with travis
pandas 0.16.2, bio 1.65
https://travis-ci.org/FRED-2/Fred2/builds/78206690#L1130
upgrading to blocker

**Comment by b-schubert** [comment]
Apparently this is caused on Linux machines by the following peptide sequence oO:

```
IHTIEPFYS
``` 

deleting the last character resolves the error.....

**Comment by b-schubert** [comment]
I boiled the problem down to Seq.__lt__. Biopython first compares the Alphabets of the two parameters. I don't know why this fails; both peptides have the same Alphabet. 

A hotfix would be to overwrite __lt__ in Peptide, Protein etc. to just comparing the sequence.

**Comment by b-schubert** [comment]
This reproduces the error on Linux machines:

```
from Fred2.Core import Peptide

#Preidctions
from Fred2.EpitopePrediction import EpitopePredictorFactory

p1 = Peptide("AAAAAAAAA")
p2 = Peptide("SYFPEITHI")

print "This should fail:", p1 <= p2
print "it has not"
sys.exit()
```

**Comment by b-schubert** [comment]
hotfixed by merge #33
