### ISSUE TITLE
Transcript IDs not found in DB in proteovariants.py script

### ISSUE THREAD

**Issue by Leon-Bichmann** [FRED-2/Fred2#189]
Variants can't be translated into protein fasta databank using the proteovariants.py script, because the IDs are not found:

```
mart_db = MartsAdapter(biomart="http://ensembl.org")  # TODO guess id_type for mart_db from accessions

transcript_gen = g.generate_transcripts_from_variants(vcfvars, mart_db, id_type=EIdentifierTypes.REFSEQ)
```

    protein_gen = g.generate_proteins_from_transcripts(transcript_gen)
    proteins = [x for x in protein_gen if x.vars]  # removing unvaried
/Library/anaconda/lib/python2.7/site-packages/Fred2/Core/Generator.py:352: UserWarning: Transcript with ID ENST00000367357 not found in DB
  warnings.warn("Transcript with ID %s not found in DB"%tId)
^CTraceback (most recent call last):
  File "ProteoVariants.py", line 415, in <module>
    __main__()
  File "ProteoVariants.py", line 227, in __main__
    proteins = [x for x in protein_gen if x.vars]  # removing unvaried
  File "/Library/anaconda/lib/python2.7/site-packages/Fred2/Core/Generator.py", line 406, in generate_proteins_from_transcripts
    for t in transcripts:
  File "/Library/anaconda/lib/python2.7/site-packages/Fred2/Core/Generator.py", line 350, in generate_transcripts_from_variants
    query = dbadapter.get_transcript_information(tId, type=id_type)
  File "/Library/anaconda/lib/python2.7/site-packages/Fred2/IO/MartsAdapter.py", line 207, in get_transcript_information
    tsvreader = csv.DictReader(urllib2.urlopen(self.biomart_url+urllib2.quote(rq_n)).read().splitlines(), dialect='excel-tab')
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Library/anaconda/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/Library/anaconda/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/Library/anaconda/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/Library/anaconda/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/Library/anaconda/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)

**Comment by Leon-Bichmann** [comment]
The problem was that the variants were annotated with ENSEMBL IDs, whereas the ID type was specified to be REFSEQ.

**Comment by b-schubert** [comment]
close?

**Comment by Leon-Bichmann** [comment]
Yes you can close both, Mathias just suggested me to open it so we keep it in memory for new people.

Best,
Leon
