### ISSUE TITLE
dependency problem of svmlight

### ISSUE THREAD

**Issue by partrita** [FRED-2/Fred2#215]
I've tried the beginners tutorials 

```python
from Fred2.Core import Allele, Peptide, Protein,generate_peptides_from_proteins
from Fred2.IO import read_lines, read_fasta
from Fred2.EpitopePrediction import EpitopePredictorFactory
```
but got a error

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-4e21da3658eb> in <module>()
      1 from Fred2.Core import Allele, Peptide, Protein,generate_peptides_from_proteins
      2 from Fred2.IO import read_lines, read_fasta
----> 3 from Fred2.EpitopePrediction import EpitopePredictorFactory
      4 get_ipython().magic(u'matplotlib inline')

C:\Users\deepthought\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\Fred2-2.0.1-py2.7.egg\Fred2\EpitopePrediction\__init__.py in <module>()

C:\Users\deepthought\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\Fred2-2.0.1-py2.7.egg\Fred2\EpitopePrediction\SVM.py in <module>()
ImportError: No module named svmlight
```

Therefore, I do `pip install svmlight`

```
(py2) C:\Users\deepthought>pip install svmlight 
Collecting svmlight
  Downloading https://files.pythonhosted.org/packages/11/05/dd324f7084b151460d1890c138fbbe07e71bcc5770b5953715090413dc52
/svmlight-0.4.tar.gz (54kB)
    100% |################################| 61kB 124kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\deepth~1\appdata\local\temp\pip-install-3pjoss\svmlight\setup.py", line 7, in <module>
        lib_sources.remove('lib/svm_loqo.c') # this is an alternate backend for SVM-Light; only
    ValueError: list.remove(x): x not in list

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\deepth~1\appdata\local\temp\pip-install-3pjoss\s
vmlight\
```
but still got a error msg.

**Comment by b-schubert** [comment]
SMVlight was unfortunately only developed for Unix-based systems.

You can use our Docker Container: https://hub.docker.com/r/aperim/immunonodes/
It comes with FRED and all other dependencies installed.
