### ISSUE TITLE
ImportError: cannot import name d2s

### ISSUE THREAD

**Issue by b-schubert** [FRED-2/Fred2#34]
```
======================================================================
ERROR: Failure: ImportError (cannot import name d2s)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/FRED-2/Fred2/Fred2/test/TestDistance2Self.py", line 10, in <module>
    from Fred2.Distance2Self.Distance2Self import Distance2Self
  File "/home/travis/build/FRED-2/Fred2/Fred2/Distance2Self/Distance2Self.py", line 11, in <module>
    from Fred2 import d2s
ImportError: cannot import name d2s
```

**Comment by b-schubert** [comment]
Works on local cluster machines.

**Comment by b-schubert** [comment]
On Mac I get the following error:

```
from Fred2 import d2s
ImportError: dlopen(/../../test_optivac/lib/python2.7/site-packages/Fred2/d2s.so, 2): no suitable image found.  Did find:
/../../lib/python2.7/site-packages/Fred2/d2s.so: mach-o, but wrong architecture
```

```file()``` on d2s.so gives me:

``` 
Fred2 schubert$ file d2s.so 
d2s.so: Mach-O bundle i386
```

**Comment by mwalzer** [comment]
obviously ARCHFLAGS does not get set correctly for mac in the setup.py compile process ... how do other packages handle mac?

**Comment by b-schubert** [comment]
@christopher-mohr  would you be willing to get dist2self cyton implementation production ready?
